name: Build and Deploy
on: 
  push:
    branches:
      - main
permissions:
  contents: write

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY}}
  REACT_APP_MESSAGE_TEMPLATE: ${{secrets.REACT_APP_MESSAGE_TEMPLATE}}
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: ask_edinburgh_client
        uses: xiaowuuu/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
# Allow repo secrets
